version: '3.8'

services:
  app:
    build: .
    ports:
      - "4400:4400"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: 'root'
      DATABASE: greenthumb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: greenthumb
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql  # Persist MySQL data
      - ./DataBase/greenthumb.sql:/docker-entrypoint-initdb.d/greenthumb.sql  # Initialize database with SQL file
